### ISSUE TITLE
mix sentences up more

### ISSUE THREAD

**Issue by vid** [seiyria/jsmegahal#3]
sorry, I don't know the technical description but I'm using jsmegahal for an irc chat bot and find it tends to repeat even long sentences as-is, even though it has lots of data. I had used the classic megahal before and it was more creative. is there some way to have it mix things up more? thanks!

**Comment by seiyria** [comment]
Not really, I don't think. I ported MegaHal pretty much exactly though so I'm not sure what sort of differences you'd notice.

**Comment by vid** [comment]
ok, must be subjective. thanks for the fun implementation though!

**Comment by seiyria** [comment]
No problem!
