### ISSUE TITLE
Are only existing sentences returned?

### ISSUE THREAD

**Issue by andreas1974** [seiyria/jsmegahal#4]
Hi!
I've been testing jsMegaHal for some hours, but it seems this implementation does not construct new sentences, is that by design or is the AI incomplete?
Since the description said "Implementation of the MegaHAL AI", I thought it was going to behave in a similar way as the real thing (MegaHal), but so far I'm only getting the existing sentences back, i.e. the ones Hal has been trained with.
The original MegaHal puts words together making new sentences based on their vicinity to other words in the training data.
Thanks,
Andreas

**Comment by seiyria** [comment]
No, it definitely does work. I've used the latest version ([sample code](https://github.com/kellyirc/kurea/blob/master/src/modules/games/MegaHalModule.coffee)) for a year prior to turning it off (it eats _way_ too much memory) and it works like a charm. It just needs a sufficiently large amount of data to work well - if you don't have any sentences with overlap in words, it can't do this very well.

**Comment by andreas1974** [comment]
I set the markov order to 2, it seems more like the good old MegaHal.
var megahal = new jsmegahal(2);
If I understand your sample code corretly you too are initiating jsmegahal with order 2.

When initiating jsmegahal with (markov order) 4, which is the default, or even 3, almost no combinations are made. So far I've seen only two combinations that were built from different sentences, with hundreds of sentences entered. Everything else has been repetitions of the same words that I entered or complete lines from the training file which contains more than 1000 sentences in Swedish.
Markov order 4 seems to be what the original MegaHal was using according to https://megahal.alioth.debian.org/How.html.

**Comment by seiyria** [comment]
Correct. I had better results from 2 - and it makes sense that you would too. It has a far lower barrier to entry. I followed the style of [JMegaHal](http://www.jibble.org/jmegahal/) when building this so it's possible it's quite a bit more strict. It's also possible that it's a bug in my implementation, but I've not looked at this in years.

**Comment by andreas1974** [comment]
Anyway, we are having fun with a couple of jsmegahal bots (set to markov order 2) in Telegram now, using "moronbot-telegram" as a link between your code and the telegram chat.
Thank you for resurrecting Megahal!

**Comment by seiyria** [comment]
Awesome! I'm glad to hear it! I did it for the projects like that, that can benefit from it. Enjoy! :D
